name             'mahjong'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures mahjong'
long_description 'Installs/Configures mahjong'
version          '0.1.0'

depends 'java', '= 1.29.0'
depends 'tomcat', '= 0.17.0'
