require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |test|
  test.rspec_opts = [].tap do |arguments|
    arguments.push('--color')
    arguments.push('--format progress')
  end.join(' ')
end

task :default => [:spec]
